### ISSUE TITLE
Memory limit?

### ISSUE THREAD

**Issue by sorendipitous** [Exormeter/12Riven_ScriptEditor#3]
![image](https://user-images.githubusercontent.com/12383421/173205101-41c30b87-2aa5-41c7-a6fd-dc7ab13c6a8a.png)
![image](https://user-images.githubusercontent.com/12383421/173205104-6839e8f9-a653-44a5-8fe8-ee193a1eba74.png)
![image](https://user-images.githubusercontent.com/12383421/173205183-3c8b7953-4e4e-4f2c-add5-1ff0240d9c51.png)
Whenever there are too many characters in a single script file, the data overwrites itself with blank space, including important system files. This has been happening primarily with the second script (Ca11b) as it is already quite large in Japanese.

Strangely enough, whenever this starts happening, the filesize increases by quite a lot more than it should despite seemingly overwriting the data. (the original size before any edits was 60kb, for note, and around 70kb just before the issue arose)

**Comment by gribnikof** [comment]
I have that problem. Please fix the scripteditor.

**Comment by Exormeter** [comment]
It is not a problem of the script editor per se, rather a limit with how the game scripts are formatted. The fist half of the script stores OP codes to be executed by the engine. The second half contains the text as strings. Gluing the string to an OP code is a 16 Bit pointer, basically the address of the string inside the script file. As soon as a script file hits over 64kb, the address space of the 16 bit pointer will overflow. This means, that scripts are currently limited to 64kb. One way of getting around this would hacking the exe of the game to load bigger script files or splitting the script file. I have looked into how scripts are loaded to implement a possible split, but it is nothing that will be fixed anytime soon.


Btw @gribnikof, are you associated with the russian translation of the game? Just wondering since I saw the editor linked on the vk page.

**Comment by gribnikof** [comment]
So it was a failed attempt. The Rb 07.BIN file has an initial size of 577 kb.
The project Tuna std. was closed.

**Comment by Exormeter** [comment]
Not sure if I understand you correctly. The initial file size of RB07 is 57.7 kb, not 577 kb, which is well below the 64 kb limit.

**Comment by gribnikof** [comment]
![07](https://user-images.githubusercontent.com/121253675/209348922-2c32cab3-a0e4-4c50-8ffd-afee9080dd3c.png)
I will let you know if I can fix this problem. But I already have 100% Japanese text from this file.

**Comment by Exormeter** [comment]
That's wired. I freshly unpacked the unmodified SCENE00.afs from an japanese copy of the game and it showes me 64 kb (rounded up) for RB07. The chinese one, where I first had a look, is 56kb , which is I thought you had misread a decimal place. 
![Screenshot 2022-12-23 151818](https://user-images.githubusercontent.com/5355243/209350371-dc1a55a5-1c0f-4d3c-b4b8-465541575647.png)

**Comment by Exormeter** [comment]
Or has it an filesize of 577kb after translating the file to russian?

**Comment by gribnikof** [comment]
Okay, well, now it all makes sense
start file size 63kb
I translate the name [Renmaru] => file size 65kb
I translate the name [Myuu] => file size 128kb
I deleted the file
I translate the name [Myuu] => file size 64kb
I translate the name [Renmaru] => file size 65kb
It's magic!
Thanks for the support.

**Comment by gribnikof** [comment]
Exormeter, if you have a fully edited file rb07 in English or Chinese, can you give access to it? I translated 32 lines of Japanese text into English (increased the file size to 119 kb). I want to try one last time.

**Comment by Exormeter** [comment]
Just wanted to let you know that I have successfully split a script into two, so the memory limit can be worked around. I need to refine the editor a bit more, but I think I can share a solution soon.

**Comment by Exormeter** [comment]
Splitting is now supported
